### ISSUE TITLE
cannot install plugin on moodle 3.8.1 (Build: 20200130)

### ISSUE THREAD

**Issue by stemiwe** [sharpchi/moodle-atto_templates4u#7]
using atto_templates version 2017103001, i just upgraded our test server from an earlier build of 3.8.1 to the latest (3.8.1 Build: 20200130), and upon upgrading, the server claimed "missing source" for the atto_templates plugin, even though the plugin was still sitting in the correct directory.

i uninstalled the plugin and tried updating to the latest version (2020013000), but now i cannot even get any version of the plugin installed - my moodle server keeps ignoring the files sitting in /lib/editor/atto/plugins/templates, and does not ever present me with the plugin install menu. other plugins install just fine.

on a different test server running moodle 3.6.7 i can install either version of the upgrade just fine, so i'm not sure if this is an issue of my specific server, or the latest moodle 3.8.1 version, or of your plugin. just wanted to report, would be great if you could tell me whether you can reproduce this problem.

**Comment by sharpchi** [comment]
Thanks for the info. Will check it out. I'm currently testing 3.8.1.

**Comment by sharpchi** [comment]
Hi @webers-technikum-wien I've tried installing/updating/uninstalling/reinstalling and am not having any issues. I wonder if the file permissions are not right on your server. One change I did make was to the file permissions, changing them from 755 to 644, which gives read/write to the owner, and read only to everyone else.

**Comment by stemiwe** [comment]
permissions seem identical to other plugins. i've never experienced this with any plugin before. will try to get to the bottom of it once i find the time.

**Comment by maxlkin** [comment]
This is affecting 3.7 too. Read and write permissions match the others. Other Atto editor plugins are recognized just fine, it is only this one that is being ignored. Tested on 3.6 where it is recognized fine, via the same install process.

Using plugin version 2020013000;

**Comment by sharpchi** [comment]
I've tried doing a clean install from the version I've uploaded to moodle.org - and that installs in M3.8 just fine
![image](https://user-images.githubusercontent.com/3774280/75793861-e0a2c600-5d67-11ea-86de-07973301cdf0.png)
![image](https://user-images.githubusercontent.com/3774280/75793887-ed271e80-5d67-11ea-9386-b7321928c358.png)
And I've tried installing from the git master version:
![image](https://user-images.githubusercontent.com/3774280/75794260-70e10b00-5d68-11ea-87c5-87bfebb5b11a.png)
![image](https://user-images.githubusercontent.com/3774280/75794289-79394600-5d68-11ea-820c-a68282891fc8.png)
And this also has installed with no issue. So I'm struggling to understand where the problem is happening. @mikechurchwood has suggested renaming the folder, and I've tried to see if there's any inconsistency with the naming, but that doesn't seem to be the case.
I'm sure you're putting the folder in the right place - /lib/editor/atto/plugins/templates
Could I ask you to uninstall - remove the folder completely - and then try again. If there are any error messages to help, that would be useful.

I can't imagine it's a PHP thing, but just to scrub that as an issue, which version of PHP are people using? I'm running PHP7.3.
thanks

**Comment by sharpchi** [comment]
OK - It seems that Moodle has recently banned "templates" as being a valid directory name for anything other than mustache templates. So this might be causing the issue. Bug tracker here: https://tracker.moodle.org/browse/MDL-67768

I'm going to have to rename the plugin.

**Comment by stemiwe** [comment]
ooooooh, thats one of those issues that are almost impossible to debug, who would ever think of that :(.

that's kinda awkward, since i guess renaming the plugin implies making a new plugin and re-uploading it to moodle.org, and their approval process takes around 5 to 6 months right now...

**Comment by sharpchi** [comment]
Possibly. I can repoint people to the new repo page. Mike Churchward spotted that. I'm going to be calling it templates4u - I should have something later today if you'd like to play.

**Comment by sharpchi** [comment]
This is now sorted and live on the Moodle repositories as atto_templates4u. Thanks for your help Mike and Webers
